export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const AUTENTICACION_USUARIO = 'AUTENTICACION_USUARIO';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';